
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.Shows.Domain.Exceptions.ServeiNoDisponible;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-10T12:44:16.683+02:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CurrencyConvertor",
                      portName = "CurrencyConvertorSoap12",
                      targetNamespace = "http://www.webserviceX.NET/",
                      wsdlLocation = "http://www.webservicex.net/currencyconvertor.asmx?wsdl",
                      endpointInterface = "net.webservicex.CurrencyConvertorSoap")
                      
public class CurrencyConvertorSoapImpl1 implements CurrencyConvertorSoap {

    private static final Logger LOG = Logger.getLogger(CurrencyConvertorSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.CurrencyConvertorSoap#conversionRate(net.webservicex.Currency  fromCurrency ,)net.webservicex.Currency  toCurrency )*
     */
    public double conversionRate(net.webservicex.Currency fromCurrency,net.webservicex.Currency toCurrency) { 
        LOG.info("Executing operation conversionRate");
        System.out.println(fromCurrency);
        System.out.println(toCurrency);
        try {
            double _return = 0.513062050421309;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
        }
		return 0;
    }
}
