
package net.webservicex;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.Shows.Domain.Model.Moneda;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-06-10T12:44:16.593+02:00
 * Generated source version: 2.6.1
 * 
 */
public final class CurrencyConvertorSoap_CurrencyConvertorSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET/", "CurrencyConvertor");

    public CurrencyConvertorSoap_CurrencyConvertorSoap_Client() {
    }

    public static double convert(Moneda divisa, Moneda moneda)  {
        URL wsdlURL = CurrencyConvertor.WSDL_LOCATION;
        
        CurrencyConvertor ss = new CurrencyConvertor(wsdlURL, SERVICE_NAME);
        CurrencyConvertorSoap port = ss.getCurrencyConvertorSoap();
        
        if (divisa.toString().equals("EUR")) {
	        if (moneda.toString().equals("USD")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.EUR;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.USD;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
	        else if (moneda.toString().equals("GBP")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.EUR;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.GBP;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
        }
        else if (divisa.toString().equals("USD")) {
	        if (moneda.toString().equals("EUR")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.USD;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.EUR;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
	        else if (moneda.toString().equals("GBP")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.USD;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.GBP;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
        }
        else if (divisa.toString().equals("GBP")){
	        if (moneda.toString().equals("EUR")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.GBP;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.EUR;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
	        else if (moneda.toString().equals("USD")) {
		        net.webservicex.Currency _conversionRate_fromCurrency = net.webservicex.Currency.GBP;
		        net.webservicex.Currency _conversionRate_toCurrency = net.webservicex.Currency.USD;
		        return port.conversionRate(_conversionRate_fromCurrency, _conversionRate_toCurrency);
	        }
        }
        return 1;
    }

}
